// Catálogo de vehículos comunes en Ecuador para el selector del configurador.
// Fuente: investigación de Antigravity (qa/vehiculos-ecuador-antigravity.md), basada en
// AEADE, INEC y prensa ecuatoriana. `desde`/`hasta` son años aproximados de venta o
// circulación en Ecuador; `hasta: null` = sigue vigente. Para agregar un modelo basta con
// añadir una línea; el cliente siempre puede elegir «Otra marca» u «Otro modelo».

export const VEHICLE_BRANDS = Object.freeze([
  { brand: "Chevrolet", logo: "./assets/marcas/chevrolet.svg", models: [{ name: "D-Max", type: "Camioneta", from: 2006, to: null }, { name: "Aveo", type: "Auto", from: 2005, to: 2020 }, { name: "Sail", type: "Auto", from: 2011, to: 2023 }, { name: "Spark", type: "Auto", from: 2003, to: 2022 }, { name: "Grand Vitara", type: "SUV", from: 2001, to: 2019 }, { name: "Tracker", type: "SUV", from: 2013, to: null }, { name: "Groove", type: "SUV", from: 2021, to: null }, { name: "Captiva", type: "SUV", from: 2007, to: null }, { name: "Onix", type: "Auto", from: 2018, to: null }, { name: "Corsa", type: "Auto", from: 1996, to: 2008 }, { name: "Luv", type: "Camioneta", from: 1989, to: 2005 }, { name: "N300", type: "Van", from: 2012, to: 2020 }, { name: "N400", type: "Van", from: 2020, to: null }, { name: "Colorado", type: "Camioneta", from: 2020, to: null }, { name: "Silverado", type: "Camioneta", from: 1995, to: null }, { name: "NHR", type: "camion liviano", from: 1998, to: null }, { name: "NKR", type: "camion liviano", from: 1998, to: null }] },
  { brand: "Kia", logo: "./assets/marcas/kia.svg", models: [{ name: "Soluto", type: "Auto", from: 2019, to: null }, { name: "Sportage", type: "SUV", from: 2005, to: null }, { name: "Rio", type: "Auto", from: 2003, to: 2023 }, { name: "Picanto", type: "Auto", from: 2005, to: null }, { name: "Sonet", type: "SUV", from: 2021, to: null }, { name: "Seltos", type: "SUV", from: 2020, to: null }, { name: "K3", type: "Auto", from: 2024, to: null }, { name: "Cerato", type: "Auto", from: 2006, to: 2022 }, { name: "Carens", type: "SUV", from: 2004, to: null }, { name: "Carnival", type: "Van", from: 2002, to: null }] },
  { brand: "Toyota", logo: "./assets/marcas/toyota.svg", models: [{ name: "Hilux", type: "Camioneta", from: 1980, to: null }, { name: "Fortuner", type: "SUV", from: 2006, to: null }, { name: "RAV4", type: "SUV", from: 1998, to: null }, { name: "Yaris", type: "Auto", from: 2000, to: null }, { name: "Corolla Cross", type: "SUV", from: 2021, to: null }, { name: "Corolla", type: "Auto", from: 1990, to: null }, { name: "Land Cruiser Prado", type: "SUV", from: 1996, to: null }, { name: "Land Cruiser", type: "SUV", from: 1985, to: null }, { name: "4Runner", type: "SUV", from: 1995, to: null }, { name: "Raize", type: "SUV", from: 2022, to: null }, { name: "Rush", type: "SUV", from: 2018, to: null }, { name: "Agya", type: "Auto", from: 2023, to: null }, { name: "Hiace", type: "Van", from: 1995, to: null }] },
  { brand: "Hyundai", logo: "./assets/marcas/hyundai.svg", models: [{ name: "Tucson", type: "SUV", from: 2005, to: null }, { name: "Accent", type: "Auto", from: 1996, to: null }, { name: "Creta", type: "SUV", from: 2016, to: null }, { name: "Grand i10", type: "Auto", from: 2014, to: null }, { name: "Santa Fe", type: "SUV", from: 2001, to: null }, { name: "Elantra", type: "Auto", from: 1998, to: null }, { name: "H1", type: "Van", from: 2008, to: 2021 }, { name: "Staria", type: "Van", from: 2022, to: null }] },
  { brand: "Great Wall", logo: null, models: [{ name: "Wingle 5", type: "Camioneta", from: 2011, to: null }, { name: "Wingle 7", type: "Camioneta", from: 2019, to: null }, { name: "Poer", type: "Camioneta", from: 2021, to: null }, { name: "Haval H6", type: "SUV", from: 2015, to: null }, { name: "Haval Jolion", type: "SUV", from: 2021, to: null }, { name: "Haval M4", type: "SUV", from: 2013, to: 2021 }, { name: "Wingle 3", type: "Camioneta", from: 2007, to: 2014 }] },
  { brand: "Nissan", logo: "./assets/marcas/nissan.svg", models: [{ name: "Frontier", type: "Camioneta", from: 1998, to: null }, { name: "X-Trail", type: "SUV", from: 2002, to: null }, { name: "Qashqai", type: "SUV", from: 2008, to: null }, { name: "Versa", type: "Auto", from: 2012, to: null }, { name: "Sentra", type: "Auto", from: 1992, to: null }, { name: "Tiida", type: "Auto", from: 2006, to: 2018 }, { name: "Kicks", type: "SUV", from: 2017, to: null }, { name: "D21", type: "Camioneta", from: 1990, to: 2008 }, { name: "Patrol", type: "SUV", from: 1990, to: null }, { name: "Urvan", type: "Van", from: 2000, to: null }] },
  { brand: "Suzuki", logo: "./assets/marcas/suzuki.svg", models: [{ name: "Grand Vitara SZ", type: "SUV", from: 2008, to: 2019 }, { name: "Jimny", type: "SUV", from: 1999, to: null }, { name: "S-Cross", type: "SUV", from: 2014, to: null }, { name: "Swift", type: "Auto", from: 2006, to: null }, { name: "Fronx", type: "SUV", from: 2023, to: null }, { name: "Grand Vitara Híbrido", type: "SUV", from: 2023, to: null }, { name: "Vitara Clásico", type: "SUV", from: 1990, to: 2006 }] },
  { brand: "Renault", logo: "./assets/marcas/renault.svg", models: [{ name: "Duster", type: "SUV", from: 2012, to: null }, { name: "Stepway", type: "Auto", from: 2010, to: null }, { name: "Sandero", type: "Auto", from: 2009, to: null }, { name: "Logan", type: "Auto", from: 2006, to: null }, { name: "Koleos", type: "SUV", from: 2009, to: null }, { name: "Oroch", type: "Camioneta", from: 2016, to: null }] },
  { brand: "Chery", logo: null, models: [{ name: "Tiggo 2", type: "SUV", from: 2017, to: null }, { name: "Tiggo 7 Pro", type: "SUV", from: 2020, to: null }, { name: "Tiggo 8 Pro", type: "SUV", from: 2019, to: null }, { name: "Tiggo 4 Pro", type: "SUV", from: 2018, to: null }, { name: "Arrizo 5", type: "Auto", from: 2017, to: null }] },
  { brand: "Volkswagen", logo: "./assets/marcas/volkswagen.svg", models: [{ name: "Gol", type: "Auto", from: 1995, to: 2023 }, { name: "Polo", type: "Auto", from: 2003, to: null }, { name: "T-Cross", type: "SUV", from: 2019, to: null }, { name: "Amarok", type: "Camioneta", from: 2010, to: null }, { name: "Tiguan", type: "SUV", from: 2009, to: null }, { name: "Taos", type: "SUV", from: 2021, to: null }, { name: "Virtus", type: "Auto", from: 2019, to: null }, { name: "Saveiro", type: "Camioneta", from: 1995, to: null }] },
  { brand: "Ford", logo: "./assets/marcas/ford.svg", models: [{ name: "F-150", type: "Camioneta", from: 1995, to: null }, { name: "Ranger", type: "Camioneta", from: 1998, to: null }, { name: "Explorer", type: "SUV", from: 1996, to: null }, { name: "EcoSport", type: "SUV", from: 2004, to: 2022 }, { name: "Escape", type: "SUV", from: 2001, to: null }, { name: "Expedition", type: "SUV", from: 1998, to: null }] },
  { brand: "JAC", logo: null, models: [{ name: "T8", type: "Camioneta", from: 2020, to: null }, { name: "T6", type: "Camioneta", from: 2016, to: null }, { name: "JS2", type: "SUV", from: 2016, to: null }, { name: "JS3", type: "SUV", from: 2016, to: null }, { name: "JS4", type: "SUV", from: 2020, to: null }, { name: "Sunray", type: "Van", from: 2015, to: null }] },
  { brand: "Mazda", logo: "./assets/marcas/mazda.svg", models: [{ name: "BT-50", type: "Camioneta", from: 2007, to: null }, { name: "Mazda 3", type: "Auto", from: 2004, to: null }, { name: "Mazda 2", type: "Auto", from: 2008, to: null }, { name: "CX-5", type: "SUV", from: 2012, to: null }, { name: "CX-30", type: "SUV", from: 2020, to: null }, { name: "Allegro", type: "Auto", from: 1995, to: 2008 }, { name: "B2600", type: "Camioneta", from: 1990, to: 2006 }] },
  { brand: "DFSK", logo: null, models: [{ name: "Glory 560", type: "SUV", from: 2018, to: null }, { name: "Glory 580", type: "SUV", from: 2017, to: null }, { name: "Glory 500", type: "SUV", from: 2021, to: null }, { name: "C37", type: "Van", from: 2014, to: null }, { name: "K01", type: "Camioneta", from: 2012, to: null }] },
  { brand: "Jetour", logo: null, models: [{ name: "X70", type: "SUV", from: 2020, to: null }, { name: "X70 Plus", type: "SUV", from: 2022, to: null }, { name: "Dashing", type: "SUV", from: 2023, to: null }, { name: "X90 Plus", type: "SUV", from: 2024, to: null }] },
  { brand: "Dongfeng", logo: null, models: [{ name: "Rich 6", type: "Camioneta", from: 2020, to: null }, { name: "T5 EVO", type: "SUV", from: 2022, to: null }, { name: "SX5", type: "SUV", from: 2018, to: null }, { name: "Joyear X3", type: "SUV", from: 2016, to: 2022 }, { name: "Captain", type: "camion liviano", from: 2012, to: null }] },
  { brand: "Mitsubishi", logo: "./assets/marcas/mitsubishi.svg", models: [{ name: "L200", type: "Camioneta", from: 1995, to: null }, { name: "Montero Sport", type: "SUV", from: 1998, to: null }, { name: "Montero Clásico", type: "SUV", from: 1992, to: 2018 }, { name: "Outlander", type: "SUV", from: 2004, to: null }, { name: "ASX", type: "SUV", from: 2011, to: null }] },
  { brand: "Shineray", logo: null, models: [{ name: "X30", type: "Van", from: 2015, to: null }, { name: "G01", type: "SUV", from: 2020, to: null }, { name: "G05", type: "SUV", from: 2021, to: null }] },
  { brand: "Changan", logo: null, models: [{ name: "CS15", type: "SUV", from: 2017, to: null }, { name: "CS35 Plus", type: "SUV", from: 2015, to: null }, { name: "CS55 Plus", type: "SUV", from: 2021, to: null }, { name: "Hunter", type: "Camioneta", from: 2020, to: null }, { name: "Alsvin", type: "Auto", from: 2021, to: null }] },
  { brand: "BYD", logo: null, models: [{ name: "Yuan Plus", type: "SUV", from: 2022, to: null }, { name: "Dolphin", type: "Auto", from: 2023, to: null }, { name: "Song Plus", type: "SUV", from: 2023, to: null }, { name: "Seagull", type: "Auto", from: 2024, to: null }, { name: "Tang", type: "SUV", from: 2022, to: null }] },
  { brand: "Hino", logo: null, models: [{ name: "Dutro 300", type: "camion liviano", from: 2003, to: null }, { name: "Serie 500", type: "camion liviano", from: 2000, to: null }] },
]);

export const CURRENT_YEAR = new Date().getFullYear();

export function findBrand(name) {
  return VEHICLE_BRANDS.find((item) => item.brand === name);
}

export function modelYears(model) {
  const last = model.to ?? CURRENT_YEAR + 1;
  const years = [];
  for (let year = last; year >= model.from; year -= 1) years.push(String(year));
  return years;
}
